title: "North Point"
email: rodrigorblx@gmail.com
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: anvoids
paginate: 30
disqus: 'north-point'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-8PEBM7CCW4

# Authors
authors:
  anvoids:
    name: Rodrigo
    display_name: anvoids
    avatar: 'assets/images/authors/anvoids.png'
    email: rodrigorblx@gmail.com
    web: https://www.roblox.com/users/148191977/profile
    twitter: https://twitter.com/anvoids
    description: "President of North Point"

# Social
social:
  discord: https://discord.gg/XtHuDWE55N/
  roblox: https://www.roblox.com/games/8318913101/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives